# Pytorch

# Pytorch Packages

 - **torch**
 - torch.autograd
 - torch.nn
 - torch.optim
 - torch.multiprocessing
 - torch.utils

# Pytorch Tensor Basic Usage

- Create Tensor
- Indexing, Joining, Slicing
- Initialization
- Math Operations

## 1. Create Tensor

### 1) random numbers

In [2]:
from __future__ import print_function
import torch

In [3]:
import numpy as np

In [3]:
# torch.rand(size)
# 0~1 사이의 연속균등분포에서 값을 뽑아 5x3 텐서를 생성합니다. ~U(0,1)
x = torch.rand(2,3)
x

tensor([[0.0398, 0.8877, 0.3485],
        [0.9069, 0.9101, 0.8245]])

In [4]:
x = np.random.rand(2,3)
x

array([[0.09898822, 0.23048509, 0.77560868],
       [0.86485078, 0.60619465, 0.41650412]])

In [7]:
# torch.randn(size)
# randn의 경우 평균은 0, 표준편차는 1인 정규분포에서 값을 가져옵니다 ~z(0,1)
x = torch.randn(2,3)
x

tensor([[ 0.1385,  1.2593, -0.5954],
        [ 0.1113,  0.7883,  0.3480]])

In [8]:
x = np.random.randn(2,3)
x

array([[-0.16151086,  2.48393292, -0.74602962],
       [ 0.5072721 ,  1.24006703,  1.51520934]])

In [5]:
# torch.randperm(n)
# 0부터 n-1까지 1씩 늘어나며 값을 랜덤으로 정렬합니다.
x = torch.randperm(5)
x

tensor([0, 2, 1, 4, 3])

### 2) empty, zeros, ones, arange, max

In [10]:
# torch.empty(size)
# 원하는 크기의 아주 작은 값을 가진 텐서를 생성합니다. dtype은 input에 따라 결정됩니다.
x = torch.empty(2,3)
x

tensor([[-1.8965e+09,  3.0739e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [11]:
x.size()

torch.Size([2, 3])

In [12]:
# torch.zeros(size)
# 원하는 크기의 0 값을 가진 텐서를 생성합니다.
x = torch.zeros(2,3)
x[0]

tensor([0., 0., 0.])

In [13]:
# torch.ones(size)
# 원하는 크기의 1의 값을 가진 텐서를 생성합니다.
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# torch.arange(start,end,step=1)
# start값부터 end값 전까지 step만큼 더하며 텐서를 생성합니다.
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [16]:
y  = np.arange(0,3,step=0.5)
y

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [17]:
y.shape == x.size()

True

In [18]:
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor)
# tensor의 최대값을 산출합니다.

x = torch.rand(2,3)
print(x)

tensor([[0.1332, 0.5962, 0.8934],
        [0.6523, 0.2250, 0.0484]])


In [22]:
# 최대값을 출력합니다.
print(torch.max(x))
print(torch.max(x).shape)

tensor(0.8934)
torch.Size([])


In [26]:
print(torch.max(x,0)[1])
print(x.size(), torch.max(x,0)[1].size())

tensor([1, 0, 0])
torch.Size([2, 3]) torch.Size([3])


In [27]:
# 위치를 출력합니다.
print(torch.max(x,1)[1])
print(x.size(), torch.max(x,1)[1].size())

tensor([2, 0])
torch.Size([2, 3]) torch.Size([2])


### 3) Tensor Data Type

| Data type               | dtype                                         | Tensor types                 |
|:-------------------------|:-----------------------------------------------|:------------------------------|
| 32-bit floating point   | ``` torch.float32 ``` or ``` torch.float ```  | ``` torch.*.FloatTensor ```  |
| 64-bit floating point   | ``` torch.float64 ``` or ``` torch.double ``` | ``` torch.*.DoubleTensor ``` |
| 16-bit floating point   | ``` torch.float16 ``` or ``` torch.half ```   | ``` torch.*.HalfTensor ```   |
| 16-bit integer (signed) | ``` torch.int16 ``` or ``` torch.short ```    | ``` torch.*.ShortTensor ```  |
| 32-bit integer (signed) | ``` torch.int32 ``` or ``` torch.int ```      | ``` torch.*.IntTensor ```    |
| 64-bit integer (signed) | ``` torch.int64 ``` or ``` torch.long ```     | ``` torch.*.LongTensor ```   |

In [5]:
# torch.empty(size, dtype=)
# torch.zeros(size, dtype=)
# torch.arange(start,end,dtype=)

# torch에서 지원하는 다양한 data type을 옵션으로 지정할 수 있습니다.

x = torch.empty(2,3, dtype=torch.float) #32bit-float
y = torch.zeros(2,3, dtype = torch.int16) # 64bit-integer
z = torch.arange(0,3,step=0.5,dtype=torch.double)

print(x)
print(y)
print(z)

tensor([[2.7829e-20, 3.0709e-41, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000], dtype=torch.float64)


In [6]:
# torch.tensor(size or list, dtype = torch.floattensor) 
# 원하는 텐서를 바로 생성합니다.
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [7]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
print(x)
x = torch.FloatTensor([2,3])
print(x)

tensor([[2.7829e-20, 3.0709e-41, 3.7835e-44],
        [0.0000e+00,        nan, 1.9375e+00]])
tensor([2., 3.])


In [8]:
# tensor.type_as(tensor_type)
# tensor 형 변환
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

In [9]:

x.to(dtype= torch.float)

tensor([2., 3.])

### 4) Tensor Size

In [11]:
# tensor.size()

x = torch.FloatTensor(10,12,3,3)

print(x.size()[:])
print(x.size()[0])

torch.Size([10, 12, 3, 3])
10


In [12]:
# x = x.new_ones(5,3, dtype=torch.double) #5,3 차원의 새로운 텐서를 생성합니다.
# print(x)

x = torch.randn_like(x,dtype=torch.float) # 같은 size에서 랜덤한 숫자로 채워진 텐서를 생성합니다.
print(x)

tensor([[[[ 3.6560e-01,  1.0681e+00, -2.7819e-01],
          [ 5.8863e-02,  1.5361e+00,  1.4315e+00],
          [-3.0110e-01, -9.4643e-01, -6.6743e-01]],

         [[-2.6165e-01, -1.0517e-01, -4.9649e-01],
          [-8.0377e-01, -1.3327e+00,  4.2442e-01],
          [-2.6757e-01, -4.8905e-01,  8.6413e-01]],

         [[-1.1156e+00,  1.3259e+00, -1.7216e-01],
          [-1.0231e+00, -1.0182e+00, -6.8003e-01],
          [ 1.6811e+00, -3.8011e-01, -3.2004e-01]],

         ...,

         [[ 3.6647e-01, -1.3097e-01, -8.7761e-01],
          [-3.2417e-01,  9.7541e-01,  6.6931e-01],
          [ 8.5957e-01,  4.9724e-01,  2.5146e-01]],

         [[ 3.7792e-01,  1.0789e+00,  3.2473e-01],
          [ 1.4239e-01,  6.9991e-01,  3.7162e-01],
          [ 2.0470e+00, -5.3240e-01,  7.9092e-01]],

         [[-2.4495e-01, -6.6210e-01, -5.5071e-01],
          [ 1.8073e-01,  3.4404e-01, -6.9609e-01],
          [ 1.5847e+00, -1.9376e-01,  7.0973e-01]]],


        [[[-5.9486e-01,  4.9647e-01, -2.0312e+00],
  

## 2. Math Operations

### 1) add, mul, div

In [13]:
# torch.add()
# 텐서의 값끼리 더합니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1, x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [15]:
x1**3

tensor([[  1.,   8.,  27.],
        [ 64., 125., 216.]])

In [16]:
#차원이 다르더라도 안쪽 차원만 같으면 연산이 가능합니다.

x = torch.rand(1,5,3) # 1은 가짜 차원이므로 1이 아닌 차원이 동일하면 연산 가능
y = torch.rand(5,3)
x, y, torch.add(x,y)

(tensor([[[0.5698, 0.5330, 0.0491],
          [0.1525, 0.4602, 0.0638],
          [0.1404, 0.0025, 0.9204],
          [0.8549, 0.2184, 0.8643],
          [0.6809, 0.4169, 0.7518]]]), tensor([[0.3343, 0.9115, 0.9684],
         [0.3148, 0.4138, 0.3877],
         [0.5348, 0.0318, 0.5916],
         [0.6530, 0.7175, 0.1536],
         [0.8544, 0.9232, 0.3934]]), tensor([[[0.9041, 1.4445, 1.0175],
          [0.4673, 0.8740, 0.4515],
          [0.6752, 0.0343, 1.5120],
          [1.5079, 0.9359, 1.0180],
          [1.5353, 1.3401, 1.1452]]]))

In [17]:
# torch.add 말고 add_의 경우에는 이러한 연산 기능이 지원되지 않습니다. 따라서 먼저 x를 같은 차원으로 바꿔줍니다.

x = torch.rand(5,3)
y.add_(x)
print(y)

tensor([[0.9036, 1.2973, 1.7285],
        [0.9411, 0.7370, 0.5941],
        [1.3657, 0.3344, 1.5553],
        [0.9273, 0.9960, 1.0996],
        [1.8141, 1.6454, 0.8395]])


In [18]:
# x 텐서의 2열을 불러옵니다. numpy 연산이 지원됩니다.

print(x)
print(x.shape)
print(x[:,1])
print(x[:,1].shape)

tensor([[0.5694, 0.3858, 0.7601],
        [0.6263, 0.3232, 0.2065],
        [0.8308, 0.3026, 0.9637],
        [0.2743, 0.2785, 0.9459],
        [0.9597, 0.7222, 0.4461]])
torch.Size([5, 3])
tensor([0.3858, 0.3232, 0.3026, 0.2785, 0.7222])
torch.Size([5])


In [19]:
# torch.mul()
# hadamard product, mxn, mxn 행렬 2개를 곱합니다. 덧셈에 대해 분배법칙을 따릅니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)
x1.size(), x2.size(), x3.size(), x1, x2, x3

(torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [20]:
# torch.mul()

x1 = torch.FloatTensor([[1,2,3,],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [21]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
# torch.div()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) pow, exp, log

In [23]:
# torch.pow(input,exponent)

x1 = torch.rand(3,4)

print(x1)
print(torch.pow(x1,2),"\n",x1**2)

tensor([[0.2428, 0.2070, 0.9757, 0.8303],
        [0.8003, 0.4307, 0.4452, 0.5081],
        [0.5891, 0.6392, 0.0595, 0.0429]])
tensor([[0.0589, 0.0428, 0.9521, 0.6894],
        [0.6404, 0.1855, 0.1982, 0.2582],
        [0.3470, 0.4085, 0.0035, 0.0018]]) 
 tensor([[0.0589, 0.0428, 0.9521, 0.6894],
        [0.6404, 0.1855, 0.1982, 0.2582],
        [0.3470, 0.4085, 0.0035, 0.0018]])


In [24]:
# torch.exp(tensor,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.exp(x1))

tensor([[0.5289, 0.2423, 0.9440, 0.7489],
        [0.6011, 0.0483, 0.0289, 0.9127],
        [0.1891, 0.8713, 0.0603, 0.1076]])
tensor([[1.6971, 1.2742, 2.5702, 2.1147],
        [1.8241, 1.0495, 1.0294, 2.4912],
        [1.2082, 2.3899, 1.0621, 1.1137]])


In [25]:
# torch.log(input,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.log(x1))

tensor([[0.3761, 0.8858, 0.8013, 0.5884],
        [0.4269, 0.2160, 0.5102, 0.3739],
        [0.0999, 0.5807, 0.3067, 0.6644]])
tensor([[-0.9780, -0.1212, -0.2215, -0.5303],
        [-0.8512, -1.5325, -0.6729, -0.9836],
        [-2.3035, -0.5436, -1.1818, -0.4089]])


In [26]:
# torch.mm(matrix1, matrix2)

x1 = torch.rand(3,4)
x2 = torch.rand(4,5)

torch.mm(x1,x2)

tensor([[1.2180, 1.5061, 1.2578, 1.3296, 1.6399],
        [0.8068, 0.9512, 1.2542, 0.9844, 1.6490],
        [1.2301, 1.2749, 0.7200, 1.2367, 1.0729]])

In [27]:
# torch.bmm(batch_matrix1, batch_matrix2)
# 매트릭스 멀티플리케이션을 10번 한것 3 by 4 @ 4 by 5
x1 = torch.rand(10,3,4)
x2 = torch.rand(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

![img](https://github.com/shwksl101/Pytorch-A-to-Z/blob/master/img/innerproduct.PNG?raw=true)

In [28]:
# torch.dot(tensor1, tensor2)

torch.dot(torch.tensor([2,3]), torch.tensor([2,1]))

tensor(7)

In [31]:
# torch.t(matrix)
# tranpose

x1 = torch.rand(3,4)
print(x1.size(), x1.t().size())

torch.Size([3, 4]) torch.Size([4, 3])


In [32]:
# torch.transpose(input,dim0,dim1)

x1 = torch.rand(10,3,4)
x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size() #contiguous

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [33]:
# torch.eig(a,eigenvectors=Flase)
# eigen_value, eigen_vector

x1 = torch.rand(2,2)

print(x1,"\n",torch.eig(x1,True))

tensor([[0.8444, 0.3986],
        [0.7639, 0.5201]]) 
 torch.return_types.eig(
eigenvalues=tensor([[1.2574, 0.0000],
        [0.1071, 0.0000]]),
eigenvectors=tensor([[ 0.6945, -0.4756],
        [ 0.7195,  0.8797]]))


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  /pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:2897.)
  


### 3) view, item

In [34]:
# view()

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # -1의 경우 다른 차원들로 유추합니다. 이 경우에는 2로 유추합니다.
print(x.size())
print(y.size(),y)
print(z.size(),z)

torch.Size([4, 4])
torch.Size([16]) tensor([-0.5105,  1.6806, -1.4155, -0.0721,  0.1559, -0.5853, -0.8591, -0.1106,
        -0.5729,  1.5301,  1.2652, -1.1429,  0.0982, -0.5755, -0.2370,  0.2887])
torch.Size([2, 8]) tensor([[-0.5105,  1.6806, -1.4155, -0.0721,  0.1559, -0.5853, -0.8591, -0.1106],
        [-0.5729,  1.5301,  1.2652, -1.1429,  0.0982, -0.5755, -0.2370,  0.2887]])


In [35]:
# item()

x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0033])
0.003332067746669054


- 더 많은 연산은 다음의 링크에서 참고하세요 https://pytorch.org/docs/stable/torch.html

## 3. Tensor to Numpy, Numpy to Tensor

In [36]:
a = torch.ones(5) # 1로 채워진 텐서를 생성합니다.
print(a)

tensor([1., 1., 1., 1., 1.])


In [37]:
# tensor.numpy()

b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [38]:
# torch.from_numpy(ndarray)

a = np.ones(5) #a와 b는 연동됩니다.
b = torch.from_numpy(a)

np.add(a,1,out=a)

print(a)
print(b) #chartensor를 제외한 모든 tensor는 numpy로의 변환을 지원합니다.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [39]:
a = torch.rand(4)
b= np.array(a)
b

array([0.6100285 , 0.5852186 , 0.54389536, 0.8709249 ], dtype=float32)

In [40]:
c = torch.tensor(b)
c

tensor([0.6100, 0.5852, 0.5439, 0.8709])

## 4. Tensor on GPU

In [42]:
torch.cuda.is_available()

True

In [53]:
a = torch.randn(1000000, device= torch.device('cuda'))
b = torch.randn(1000000).cuda()
c = a * b
d  = a.cpu()* b.cpu()
c.size()

torch.Size([1000000])

In [41]:
x= torch.FloatTensor([[1,2,3],[4,5,6]])

if torch.cuda.is_available():
    x_cuda = x.cuda()
else:
    x_cuda = x.cpu()
    
print(x_cuda)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu")) #.to 기능을 tensor를 GPU로 연산할 수 있습니다
    print(z.to("cuda"))

In [58]:
torch.device("cuda:10") # Gpu 가 여러개 있을 때, 특정 Gpu를 지정하는 방법 :숫자 -> 다른 디바이스끼리는 연산이 불가능하다!

device(type='cuda', index=10)

## 5. Indexing, Slicing, Joining

### 1) Indexing

In [60]:
# tensor.index_select(input,dim,index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3])) #0차원에서 , 0,3번 째를 가져온다. 
out1 =x[[0,3], : ]
# index는 꼭 Longtensor로 입력해야 합니다.

print(x.size(), out.size())
print(x, "\n", out)
print(x, '\m', out1)

torch.Size([4, 3]) torch.Size([2, 3])
tensor([[0.7318, 0.8095, 0.7580],
        [0.3087, 0.4476, 0.9985],
        [0.9728, 0.6073, 0.2416],
        [0.9507, 0.3791, 0.7065]]) 
 tensor([[0.7318, 0.8095, 0.7580],
        [0.9507, 0.3791, 0.7065]])
tensor([[0.7318, 0.8095, 0.7580],
        [0.3087, 0.4476, 0.9985],
        [0.9728, 0.6073, 0.2416],
        [0.9507, 0.3791, 0.7065]]) \m tensor([[0.7318, 0.8095, 0.7580],
        [0.9507, 0.3791, 0.7065]])


In [62]:
a = torch.eye(5)
a[[0,1,2,3],[0,1,2,4]] # (0,0) , (1,1) ,(2,2),(3,4) 동시에 여러개를 인덱싱하는 방법

tensor([1., 1., 1., 0.])

In [63]:
print(x.size(),'\n', x)
print(x[:,0].size(),x[:,0])
print(x[0,:].size(),x[0,:])
print(x[0:2,0:2].size(),'\n', x[0:2,0:2])

torch.Size([4, 3]) 
 tensor([[0.7318, 0.8095, 0.7580],
        [0.3087, 0.4476, 0.9985],
        [0.9728, 0.6073, 0.2416],
        [0.9507, 0.3791, 0.7065]])
torch.Size([4]) tensor([0.7318, 0.3087, 0.9728, 0.9507])
torch.Size([3]) tensor([0.7318, 0.8095, 0.7580])
torch.Size([2, 2]) 
 tensor([[0.7318, 0.8095],
        [0.3087, 0.4476]])


### 2) Joining

In [64]:
# torch.cat(seq, dim=0)
# dim을 기준으로 tensor를 합칩니다.
# dim = 0은 행, dim = 1은 열 기준입니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)
z2 = torch.cat([x,y],dim = 1)

print(x)
print(y)
print(z1)
print(z2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


In [66]:
# torch.stack(sequence,dim=0)
# dim을 기준으로 쌓습니다.

x = torch.FloatTensor([1,2,3])
x_stack = torch.stack([x,x],dim=0)
x_stack2 = torch.stack([x,x],dim=1)

print(x_stack,"\n",x_stack2)

tensor([[1., 2., 3.],
        [1., 2., 3.]]) 
 tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])


### 3) Slicing

In [69]:
# torch.chunk(tensor, chunks, dim=0)
# tensor를 chunk 단위로 쪼갭니다. chunk 개수 만큼 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x_1, x_2 = torch.chunk(z1,2,dim=0) # 동일한 사이즈로 슬라이싱하는 방법 :chunk
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1)
print(x_1,x_2)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])
tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [67]:
# torch.split(tensor,split_size,dim=0) 각 size가 split_size만큼인 것을 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x1,x2 = torch.split(z1,2,dim=0)
y1,y2 = torch.split(z1,2,dim=1)

print(z1)
print(x1)
print(x2)
print(y1)
print(y2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


### 4) squeezing

In [70]:
# torch.squeeze(input, dim=None)
# 1짜리 차원을 줄입니다.

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [71]:
# torch.unsqueeze(input,dim=None)
# 1짜리 차원을 더합니다.

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x.size(), x2.size()

(torch.Size([2, 3]), torch.Size([1, 10, 3, 4]))

## 6. Initialization

In [72]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal_(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant_(torch.FloatTensor(3,4),3.1415)

x1,x2,x3

(tensor([[5.8906, 0.4615, 1.6764, 8.5418],
         [3.4401, 2.1966, 6.5125, 6.9531],
         [1.7302, 8.9788, 1.2220, 4.1279]]),
 tensor([[ 0.4277, -0.1848,  0.0410,  0.3051],
         [-0.0955, -0.0173,  0.0931, -0.4785],
         [ 0.3193,  0.2456,  0.1070,  0.0555]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

In [73]:
a = torch.randn(3,4)

x1 = init.uniform_(a.clone(),a=0,b=9) 
x2 = init.normal_(a.clone(),std=0.2)
x3 = init.constant_(a.clone(),3.1415)

x1,x2,x3

(tensor([[7.3033, 7.4332, 0.4677, 7.4304],
         [3.7330, 5.8346, 4.0714, 3.9848],
         [6.8912, 7.6912, 1.8050, 7.8047]]),
 tensor([[ 0.0091, -0.2225, -0.0228,  0.2197],
         [-0.2433,  0.2162, -0.0169, -0.0464],
         [ 0.2536, -0.1733,  0.2892, -0.2588]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))